#pragma once
#include "CoreMinimal.h"
#include "EKeySettings.generated.h"

UENUM(BlueprintType)
enum class EKeySettings : uint8 {
    MoveForward,
    MoveBack,
    MoveLeft,
    MoveRight,
    Dash,
    Jump,
    MenuL,
    MenuR,
    ChangePalette,
    UseItem,
    Action,
    Cancel,
    MenuPause,
    ItemMenuUp,
    ItemMenuDown,
    ItemMenuLeft,
    ItemMenuRight,
    CameraUp,
    CameraDown,
    CameraLeft,
    CameraRight,
    MenuX,
    MenuY,
    MinimapDispChange,
    SelectJobL,
    SelectJobU,
    SelectJobR,
    RotateL,
    RotateR,
    Attack,
    LockOn,
    LockOnNext,
    LockOnPrev,
    SkillL,
    SkillU,
    SkillR,
    SkillB,
    CharacterSpecial1,
    CharacterSpecial2,
    CharacterVehicle,
    KeySettingReset,
    KeySettingRemove,
    CharacterAction,
};

