#pragma once
#include "CoreMinimal.h"
#include "EMapIconListKind.generated.h"

UENUM(BlueprintType)
enum class EMapIconListKind : uint8 {
    Player,
    Fear,
    Quest,
    QuestMS,
    QuestCQ,
    QuestTQ,
    Memo,
    MiniEvent,
    Monolight,
    AreaChange,
    Gimmick,
    Ladder,
    Bridge,
    Inn,
    Shop,
    Blacksmith,
    Carpenter,
    House,
    Wonder,
    Fishing,
    Gathering,
    Mining,
    TreasureBox,
    CoronelShop,
    RepairLv1,
    RepairLv2,
    BombLv1,
    BombLv2,
    Switch,
    MonolightWind,
    MonolightWinter,
    Door,
    DoorClose,
    DoorLockKey,
    DoorLockSwitch,
    SwitchDoorOpen,
    SwitchDoorClose,
    PlantWallRed,
    PlantWallBlue,
    Fountain,
    Transporter,
    Maze,
    OrderCook,
    OrderFish,
    Unknown,
    QuestTQStart,
    QuestTQInProgress,
    QuestTQReward,
    Investigation,
};

