#pragma once
#include "CoreMinimal.h"
#include "EScriptCommand.generated.h"

UENUM(BlueprintType)
enum class EScriptCommand : uint8 {
    Idle,
    Start,
    End,
    TermTextWindow,
    SetBustup,
    SetBustupPosition,
    SetTextMessage,
    SetTextName,
    SetMessageWindowQuake,
    SetBustupQuake,
    RemoveBustup,
    MoveBustupPos,
    SetSelect,
    CharSetupForEvent,
    MesSendMarkDisp,
    AllClear,
    SetSystemMessage,
    LogDisp,
    Sleep,
    Turn,
    Anim,
    LevelSequence,
    Subtitle,
    CharMove,
    CharMoveWait,
    TrackCamera,
    ReturnGameCamera,
    CameraShake,
    CharLook,
    Fade,
    CharSpawn,
    CharDestroy,
    CharVisible,
    Map,
    CharCollision,
    Shop,
    ShippingBox,
    Effect,
    Enemy,
    FOV,
    Craft,
    BlendSpace,
    MapObjCollision,
    BgMask,
    Schedule,
    Wbp,
    CharLookAll,
    Etc,
    Mailbox,
    QuestGuide,
    CharMesh,
    Bg,
    CharEtc,
    CallEtc,
    UmgEtc,
    ActorEtc,
    DebugEtc,
    WaitEtc,
    Count,
};

