#pragma once
#include "CoreMinimal.h"
#include "EDirectInputPadKeyNames.generated.h"

UENUM(BlueprintType)
enum EDirectInputPadKeyNames {
    DIGamePad_AXIS_X,
    DIGamePad_AXIS_Y,
    DIGamePad_AXIS_Z,
    DIGamePad_ROT_X,
    DIGamePad_ROT_Y,
    DIGamePad_ROT_Z,
    DIGamePad_Button1,
    DIGamePad_Button2,
    DIGamePad_Button3,
    DIGamePad_Button4,
    DIGamePad_Button5,
    DIGamePad_Button6,
    DIGamePad_Button7,
    DIGamePad_Button8,
    DIGamePad_Button9,
    DIGamePad_Button10,
    DIGamePad_Button11,
    DIGamePad_Button12,
    DIGamePad_Button13,
    DIGamePad_Button14,
    DIGamePad_Button15,
    DIGamePad_Button16,
    DIGamePad_Button17,
    DIGamePad_Button18,
    DIGamePad_Button19,
    DIGamePad_Button20,
    DIGamePad_Button21,
    DIGamePad_Button22,
    DIGamePad_Button23,
    DIGamePad_Button24,
    DIGamePad_Button25,
    DIGamePad_Button26,
    DIGamePad_Button27,
    DIGamePad_Button28,
    DIGamePad_Button29,
    DIGamePad_Button30,
    DIGamePad_Button31,
    DIGamePad_Button32,
    DIGamePad_POV_Up,
    DIGamePad_POV_Right,
    DIGamePad_POV_Down,
    DIGamePad_POV_Left,
    DIGamePad_END,
    DIGamePad_MAX UMETA(Hidden),
};

